import { eq } from 'drizzle-orm';
import { Asset } from 'expo-asset';

import { db } from '@/db/client';
import { addSegment } from '@/db/drafts';
import { projects } from '@/db/schema';
import { absolutize, copyIntoSegments, deleteDraftDir, thumbRelPath } from '@/utils/file-store';
import { generateThumbnailFile, getDurationMs } from '@/utils/video';

// Dev-only helpers (§1.0b): seed one curated draft of bundled sample clips so the timeline
// editor is exercisable on a simulator with no camera. Gate every caller behind `__DEV__`.

const SEED_DRAFT_ID = 'dev-seed';
const SPEED_UNIFORM_DRAFT_ID = 'dev-seed-speed-uniform';
const SPEED_MIXED_DRAFT_ID = 'dev-seed-speed-mixed';
const WILD_IMPORTS_DRAFT_ID = 'dev-seed-wild-imports';

/** A bundled sample clip: `module` is the Metro asset module id from `require(...)`. */
type SeedFixture = { readonly module: number; readonly label: string };

/**
 * Bundled sample clips, laid into the seed draft in array order. Pick clips with
 * **deliberately mismatched** resolution / fps / codec / orientation so they also stress the
 * export normalization path (§1.0b). Drop the files in `assets/dev/` and list them here.
 *
 * `require()` of a bundled `.mp4` returns an asset module id (resolved by metro at build time),
 * so paths must be static string literals — no variables, no globbing.
 */
const FIXTURES: readonly SeedFixture[] = [
  // primary surface: short-form portrait (matches the recorder / iPhone Camera — coded landscape
  // + 90deg rotation metadata, QuickTime container). The h264 one mirrors this recorder exactly.
  {
    module: require('../../assets/dev/portrait-1080p-30fps-h264.mp4'),
    label: 'portrait 1080p 30fps h264 (recorder match)',
  },
  {
    module: require('../../assets/dev/portrait-1080p-30fps-hevc.mp4'),
    label: 'portrait 1080p 30fps hevc (iPhone default)',
  },
  {
    module: require('../../assets/dev/portrait-1080p-60fps-hevc.mp4'),
    label: 'portrait 1080p 60fps hevc',
  },
  {
    module: require('../../assets/dev/portrait-4k-60fps-hevc.mp4'),
    label: 'portrait 4k 60fps hevc',
  },
  // added later from Photos / shared: landscape to normalize into the portrait timeline
  {
    module: require('../../assets/dev/landscape-1080p-30fps-h264.mp4'),
    label: 'landscape 1080p 30fps h264 (shared mp4)',
  },
  {
    module: require('../../assets/dev/landscape-4k-30fps-hevc.mp4'),
    label: 'landscape 4k 30fps hevc (photos)',
  },
];

// --- Speed-test drafts (§1.0b) ---------------------------------------------------------------
// Two large drafts (~20 segments / ~2 min) for measuring merge SPEED at a realistic scale.
// Clips are short (~6s) and generated by scripts/make-speed-fixtures.sh into assets/dev/speed/.
// Each module is referenced many times — `seedModules` copies a fresh file per segment, so the
// bundle only carries one clip per distinct format while the draft still holds 20 segments.

const SPEED = {
  h264: require('../../assets/dev/speed/portrait-h264.mp4') as number, // recorder match — the dominant clip
  hevc: require('../../assets/dev/speed/portrait-hevc.mp4') as number,
  p60: require('../../assets/dev/speed/portrait-60.mp4') as number,
  p4k: require('../../assets/dev/speed/portrait-4k.mp4') as number,
  land1080: require('../../assets/dev/speed/landscape-1080.mp4') as number,
  land4k: require('../../assets/dev/speed/landscape-4k.mp4') as number,
};

// Dev sample 2: 20× the same recorder-match clip → one shared signature → the lossless
// passthrough join (production fast path). Exercises how the fast path scales to a 2-min draft.
const SPEED_UNIFORM_MODULES: readonly number[] = Array.from({ length: 20 }, () => SPEED.h264);

// Dev sample 3: 14× recorder-match portrait (dominant) + 6 interleaved outliers → selective
// conform re-encodes only the outliers, then passthrough-joins. Real-world mixed-format cost.
const SPEED_MIXED_MODULES: readonly number[] = [
  SPEED.h264,
  SPEED.h264,
  SPEED.hevc,
  SPEED.h264,
  SPEED.h264,
  SPEED.p60,
  SPEED.h264,
  SPEED.h264,
  SPEED.p4k,
  SPEED.h264,
  SPEED.h264,
  SPEED.land1080,
  SPEED.h264,
  SPEED.h264,
  SPEED.hevc,
  SPEED.h264,
  SPEED.h264,
  SPEED.land4k,
  SPEED.h264,
  SPEED.h264,
];

// --- Wild-import draft (§1.0b) ----------------------------------------------------------------
// One clip per hostile real-world import format (generated by scripts/make-import-fixtures.sh
// into assets/dev/import/) — HDR 10-bit, fps outliers/VFR, messaging/screen-rec geometry,
// rotation variants, and audio outliers. Together with the recorder-adjacent FIXTURES above,
// this is the acceptance corpus for import normalization + merge + upload compression: every
// clip here must survive import → (normalize) → merge → upload without manual intervention.

const WILD_IMPORT_FIXTURES: readonly SeedFixture[] = [
  {
    module: require('../../assets/dev/import/hdr-hlg-portrait-1080p-30-hevc10.mp4'),
    label: 'HDR HLG 10-bit portrait 1080p30 hevc (iPhone 12+ default)',
  },
  {
    module: require('../../assets/dev/import/hdr-pq-landscape-4k-30-hevc10.mp4'),
    label: 'HDR PQ 10-bit landscape 4k30 hevc (HDR10 download)',
  },
  {
    module: require('../../assets/dev/import/slomo-portrait-1080p-120-h264.mp4'),
    label: 'slo-mo portrait 1080p 120fps h264',
  },
  {
    module: require('../../assets/dev/import/whatsapp-848x464-30-h264-baseline.mp4'),
    label: 'WhatsApp-style 848x464 baseline h264, 44.1k audio',
  },
  {
    module: require('../../assets/dev/import/screenrec-portrait-886x1920-60-h264.mp4'),
    label: 'screen-rec 886x1920 60fps (baked portrait, no rotation tag)',
  },
  {
    module: require('../../assets/dev/import/vfr-portrait-1080p-h264.mp4'),
    label: 'VFR portrait 1080p h264 (irregular frame timing)',
  },
  {
    module: require('../../assets/dev/import/timelapse-landscape-1080p-30-hevc-noaudio.mp4'),
    label: 'timelapse landscape 1080p30 hevc, NO audio',
  },
  {
    module: require('../../assets/dev/import/opus-landscape-1080p-30-h264.mp4'),
    label: 'Opus-in-mp4 landscape 1080p30 h264 (download)',
  },
  {
    module: require('../../assets/dev/import/rot270-portrait-1080p-30-hevc.mp4'),
    label: 'portrait via rotation=270 1080p30 hevc',
  },
  {
    module: require('../../assets/dev/import/square-720x720-30-h264.mp4'),
    label: 'square 720x720 30fps h264',
  },
  {
    module: require('../../assets/dev/import/ntsc-landscape-1080p-2997-h264.mp4'),
    label: 'NTSC 29.97fps landscape 1080p h264',
  },
  {
    module: require('../../assets/dev/import/mono44k-portrait-1080p-30-h264.mp4'),
    label: 'mono 44.1kHz audio portrait 1080p30 h264',
  },
];

/**
 * Create one draft from a list of bundled clip modules, laid out in array order. Idempotent on
 * `draftId` (re-pressing is a no-op once it exists). The same module may appear multiple times —
 * each entry is copied to its own segment file. Returns the draft id (or undefined if empty).
 */
async function seedModules(
  draftId: string,
  name: string,
  modules: readonly number[],
): Promise<string | undefined> {
  if (modules.length === 0) {
    console.warn('[seed] no modules to seed — generate clips and list them in src/dev/seed.ts');
    return;
  }

  const existing = await db
    .select({ id: projects.id })
    .from(projects)
    .where(eq(projects.id, draftId));
  if (existing.length > 0) return draftId;

  await db.insert(projects).values({ id: draftId, name });

  for (let i = 0; i < modules.length; i++) {
    const asset = Asset.fromModule(modules[i]);
    await asset.downloadAsync(); // copies the bundled clip into the cache, populating localUri
    if (!asset.localUri) continue;

    const segmentId = `${draftId}-${i}`;
    const originalFilename = await copyIntoSegments(asset.localUri, draftId, segmentId);
    const durationMs = await getDurationMs(absolutize(originalFilename));
    const thumbRel = thumbRelPath(draftId, segmentId);
    const ok = await generateThumbnailFile(absolutize(originalFilename), absolutize(thumbRel));
    await addSegment(draftId, {
      id: segmentId,
      originalFilename,
      durationMs,
      thumbnail: ok ? thumbRel : null,
    });
  }

  return draftId;
}

/**
 * Add the curated sample draft, once. Idempotent: a fixed draft id means pressing the seed
 * button repeatedly never litters duplicates — if it already exists this is a no-op.
 * Returns the seed draft id (or undefined when no fixtures are wired up yet).
 */
export function seedDraft(): Promise<string | undefined> {
  return seedModules(
    SEED_DRAFT_ID,
    'Dev sample',
    FIXTURES.map((f) => f.module),
  );
}

/** Dev sample 2 — uniform recorder-match clips (fast passthrough join). */
export function seedSpeedUniform(): Promise<string | undefined> {
  return seedModules(SPEED_UNIFORM_DRAFT_ID, 'Dev sample 2 (uniform)', SPEED_UNIFORM_MODULES);
}

/** Dev sample 3 — realistic mixed formats (selective conform of the outliers). */
export function seedSpeedMixed(): Promise<string | undefined> {
  return seedModules(SPEED_MIXED_DRAFT_ID, 'Dev sample 3 (mixed)', SPEED_MIXED_MODULES);
}

/** Dev sample 4 — wild import formats (HDR, VFR, fps/geometry/audio outliers). */
export function seedWildImports(): Promise<string | undefined> {
  return seedModules(
    WILD_IMPORTS_DRAFT_ID,
    'Dev sample 4 (wild imports)',
    WILD_IMPORT_FIXTURES.map((f) => f.module),
  );
}

/** Wipe all drafts (metadata) and the seed drafts' clip dirs, so a re-seed starts clean. */
export async function clearDrafts(): Promise<void> {
  await db.delete(projects);
  deleteDraftDir(SEED_DRAFT_ID);
  deleteDraftDir(SPEED_UNIFORM_DRAFT_ID);
  deleteDraftDir(SPEED_MIXED_DRAFT_ID);
  deleteDraftDir(WILD_IMPORTS_DRAFT_ID);
}
